title: My Blog
description: A professional GitHub Markdown blog
author: Your Name
theme: minima
markdown: kramdown
github_username: twh4t
twitter_username: yourusername
linkedin_username: yourusername
email: your@email.com
